---
- name: Paketliste aktualisieren
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: Administrationswerkzeuge installieren
  ansible.builtin.apt:
    name: "{{ common_packages }}"
    state: present
  become: true
