---
- name: Server-Basiskonfiguration anwenden
  hosts: datacenter
  gather_facts: true

  roles:
    - role: common
      tags:
        - common

    - role: webserver
      tags:
        - webserver

    - role: health_check
      tags:
        - health_check
